---
name: Maven package and build container

on:
  push:
    branches: ["main"]
  # Allow manual workflow run
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of
          # changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Dependency Review
        uses: actions/dependency-review-action@v2

  mvn-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload packaged jar file
        uses: actions/upload-artifact@v3
        with:
          name: mvn-target
          path: target/*.jar

  docker-build:
    needs: mvn-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download packaged jar file
        uses: actions/download-artifact@v3
        with:
          name: mvn-target
          path: target

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jspoacacr.azurecr.io
          username: ${{ secrets.JSBOACA_REGISTRY_USERNAME }}
          password: ${{ secrets.JSBOACA_REGISTRY_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jsboacacr.azurecr.io/jsboaca:${{github.sha}}, jsboacacr.azurecr.io/jsboaca:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JSBOACA_AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure Container Apps app
        uses: azure/CLI@v1
        with:
          inlinescript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n jsboaca -g jsboacarg --server jsboacacr.azurecr.io --username  ${{ secrets.JSBOACA_REGISTRY_USERNAME }} --password ${{ secrets.JSBOACA_REGISTRY_PASSWORD }}
            az containerapp update -n jsboaca -g jsboacarg --image jsboacacr.azurecr.io/jsboaca:${{github.sha}}
